//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingEntities : DbContext
    {
        public TrainingEntities()
            : base("name=TrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Category_Details> Category_Details { get; set; }
        public virtual DbSet<Company_Details> Company_Details { get; set; }
        public virtual DbSet<Customer_Details> Customer_Details { get; set; }
        public virtual DbSet<Products_Details> Products_Details { get; set; }
        public virtual DbSet<Supplier_Details> Supplier_Details { get; set; }
        public virtual DbSet<Units_Details> Units_Details { get; set; }
        public virtual DbSet<Purchase_Bill> Purchase_Bill { get; set; }
        public virtual DbSet<Purchase_Bill_Item> Purchase_Bill_Item { get; set; }
    }
}
