//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_Details()
        {
            this.Purchase_Bill_Item = new HashSet<Purchase_Bill_Item>();
            this.Sales_Bill_item = new HashSet<Sales_Bill_item>();
        }
    
        public int Product_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        public virtual Company_Details Company_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Bill_Item> Purchase_Bill_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Bill_item> Sales_Bill_item { get; set; }
    }
}
