//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Details
    {
        public int Product_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        public virtual Company_Details Company_Details { get; set; }
    }
}
