//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Bill
    {
        public int Bill_No { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GST_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Transport_Charges { get; set; }
        public Nullable<decimal> Other_Expenses { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<int> Company_Id { get; set; }
    
        public virtual Supplier_Details Supplier_Details { get; set; }
    }
}
