//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Details
    {
        public int Stock_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> Purchase_Bill_ID { get; set; }
        public Nullable<int> Sales_Bill_ID { get; set; }
        public Nullable<decimal> Total_Quantity { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<int> Item_ID { get; set; }
    
        public virtual Sales_Bill Sales_Bill { get; set; }
        public virtual Stock_Details Stock_Details1 { get; set; }
        public virtual Stock_Details Stock_Details2 { get; set; }
    }
}
