//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units_Details
    {
        public int Unit_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Company_Details Company_Details { get; set; }
    }
}
